#!/usr/bin/env python3
"""
Build config/nav2_switching.yaml from the three tuned single-controller configs.

The switching configuration loads all three controllers into one
controller_server, under the plugin ids RPP, MPPI and DWB, each with exactly
the parameters of its FollowPath block in config/nav2_<controller>_fair.yaml.
Everything else is taken from nav2_rpp_fair.yaml; the three files agree on
all of it except min_y_velocity_threshold, which is 0.0 here (it has no
effect on a differential drive robot, whose lateral velocity is always 0).

All four configurations of the controller comparison (RPP-only, MPPI-only,
DWB-only and switching) run on this one file, so they differ only in which
controller drives when. Re-run this script after re-tuning any controller;
test/test_switching_config.py fails while the files are out of sync.

    python3 scripts/generate_switching_config.py
"""

import os

import yaml

PLUGINS = {'RPP': 'rpp', 'MPPI': 'mppi', 'DWB': 'dwb'}
HEADER = """\
# GENERATED by scripts/generate_switching_config.py - do not edit by hand.
# All three tuned controllers in one controller_server, as plugin ids RPP,
# MPPI and DWB, each with the FollowPath parameters of its
# config/nav2_<controller>_fair.yaml (see those files for comments). The
# rest is nav2_rpp_fair.yaml. Used by controller:=switching.
"""


def build(config_dir):
    def load(name):
        with open(os.path.join(config_dir, f'nav2_{name}_fair.yaml')) as f:
            return yaml.safe_load(f)

    out = load('rpp')
    server = out['controller_server']['ros__parameters']
    del server['FollowPath']
    server['min_y_velocity_threshold'] = 0.0
    server['controller_plugins'] = list(PLUGINS)
    for plugin, name in PLUGINS.items():
        server[plugin] = load(name)['controller_server']['ros__parameters'][
            'FollowPath']
    return out


def main():
    config_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              '..', 'config')
    path = os.path.join(config_dir, 'nav2_switching.yaml')
    with open(path, 'w') as f:
        f.write(HEADER)
        yaml.safe_dump(build(config_dir), f, sort_keys=False)
    print(f'Wrote {os.path.normpath(path)}')


if __name__ == '__main__':
    main()
